### ISSUE TITLE
中文绘制不全

### ISSUE THREAD

**Issue by manateelazycat** [mumu-lhl/eaf-pyqterminal#1]
![截图 2023-05-31 16-27-12](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/79004ce7-482c-4dec-9da7-21beb45d7f57)

ls的时候，英文绘制没有问题，但是中文只绘制了左边的一半

**Comment by mumu-lhl** [comment]
在最新的 commit 中采用单个字符单独绘制，然而绘制的宽度是英文字母的，所以会出现这个问题。

可以尝试不用最新的 commit 暂时解决这个问题。我会在下一个 commit 中改回原来的渲染方式。

**Comment by manateelazycat** [comment]
赞👍

**Comment by mumu-lhl** [comment]
8c3b06c 中已经修复了这个问题
