### ISSUE TITLE
分屏以后， 中间有红线

### ISSUE THREAD

**Issue by manateelazycat** [mumu-lhl/eaf-pyqterminal#17]
重现方式：

1. 打开终端输入 ls -al
2. 上下分屏

这时可以看到中间有红线， 如下图所示

![截图 2023-06-17 20-23-24](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/3aea0b35-f3de-4bd0-b686-d5f1fb104628)

**Comment by mumu-lhl** [comment]
这大概不是 EAF PyQterminal 的红线，而应该是 awesome-tray 的

**Comment by manateelazycat** [comment]
是终端区域的中间的红线

**Comment by mumu-lhl** [comment]
这个太细了，刚刚没看出来 😅。看上去和 #18 挺像的，明天测试下，看看是什么原因

**Comment by mumu-lhl** [comment]
89b9c54 应该能修复这个问题

**Comment by manateelazycat** [comment]
![截图 2023-06-17 23-23-54](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/bc6dbe86-1d95-41c4-ab87-52fd79b99c94)
![截图 2023-06-17 23-24-01](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/035a1f64-73db-4128-8100-082fa99a07b1)

注意看第一张图 eaf_pyqterm_backend.py 有下划线， 分屏后下划线没有了。

**Comment by manateelazycat** [comment]
终端中间的红线是没有了， 但是每行的渲染感觉不对， 分屏的时候， 每行的Y坐标会细微的抖动。

**Comment by mumu-lhl** [comment]
更新一下试试，这个问题应该已经修好了

**Comment by manateelazycat** [comment]
这个修好了。

**Comment by manateelazycat** [comment]
最新版，文字下划线绘制还是会丢，特别是分屏后

**Comment by mumu-lhl** [comment]
这个字体的下划线看起来有点特殊，位置低于其他字符，这会导致 EAF PyQterminal 在渲染下一行时可能会覆盖掉上一行的下划线。我用 Fira Code 就没有这个问题

但是也是有解决办法的，例如从下往上渲染，不过有些情况下，下划线还是会被覆盖掉

**Comment by manateelazycat** [comment]
换了个字体果然好了 https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Regular/FiraCodeNerdFontMono-Regular.ttf
