### ISSUE TITLE
分屏后， 切换buffer， 终端绘制会出现花屏现象

### ISSUE THREAD

**Issue by manateelazycat** [mumu-lhl/eaf-pyqterminal#18]
![截图 2023-06-17 20-24-46](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/085e4f8a-bcdc-4004-84bf-ab194edfcef2)

重现方式：

1. 打开终端， 输入 ls -al
2. 分屏
3. 然后来回切换标签， 多切几次就会发生花屏现象

**Comment by mumu-lhl** [comment]
试试 89b9c54，应该能修复这个问题

**Comment by manateelazycat** [comment]
![截图 2023-06-17 23-24-01](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/d3a98f71-4528-4db0-ab91-f7a277168663)
![截图 2023-06-17 23-35-19](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/3a8c96a0-f2c7-4ba4-9873-c2644d2059a2)
![截图 2023-06-17 23-35-28](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/baaf7fed-3ac1-4b5c-be64-112435989bf7)

重现方式：

1. 打开EAF文件管理器
2. 打开终端， 输入 ls -al
3. 分屏
4. 然后来回切换标签， 多切几次就会发生终端没有内容或者终端窗口显示相邻文件管理器的内容

**Comment by manateelazycat** [comment]
EAF中， 当一个隐藏的 view 重新显示时， 会调用 Buffer 的 some_view_show 接口。
我感觉这个bug需要自定义 some_view_show 的实现， some_view_show 里面要调用 screen 重新渲染的代码。

**Comment by mumu-lhl** [comment]
试试 6a5f7e5

**Comment by manateelazycat** [comment]
> ![截图 2023-06-17 23-24-01](https://user-images.githubusercontent.com/237487/246618800-d3a98f71-4528-4db0-ab91-f7a277168663.png) ![截图 2023-06-17 23-35-19](https://user-images.githubusercontent.com/237487/246618802-3a8c96a0-f2c7-4ba4-9873-c2644d2059a2.png) ![截图 2023-06-17 23-35-28](https://user-images.githubusercontent.com/237487/246618806-baaf7fed-3ac1-4b5c-be64-112435989bf7.png)
> 
> 重现方式：
> 
> 1. 打开EAF文件管理器
> 2. 打开终端， 输入 ls -al
> 3. 分屏
> 4. 然后来回切换标签， 多切几次就会发生终端没有内容或者终端窗口显示相邻文件管理器的内容

更新最新版依然有这个问题。

提供一个线索， 当遇到这个问题的时候， ls -al 一下， 或者 clear 一下， 上下两个终端的内容都会恢复正常。

**Comment by mumu-lhl** [comment]
产生这个 bug 的原因与字体大小还有些关系，当我把字体大小设置为 18 时没有出现任何问题，设置为 24 时就出现了这个 bug

**Comment by mumu-lhl** [comment]
现在应该已经没问题了

**Comment by manateelazycat** [comment]
这个好了
