### ISSUE TITLE
能否支持图标显示？

### ISSUE THREAD

**Issue by manateelazycat** [mumu-lhl/eaf-pyqterminal#2]
![截图 2023-06-02 22-06-34](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/3ac0c044-e2c3-4823-a30b-ba9489149bb3)

左边是 pyqterminal zsh 的图标状态， 右边是外部中断模拟器的图标状态

**Comment by mumu-lhl** [comment]
在我这边没法复现，能够正常显示图标。
可以尝试把字体换成带 Nerd Font 的，看看能不能正常显示。

**Comment by manateelazycat** [comment]
添加了 Nerd Font 以后就好了， 感谢感谢。
