### ISSUE TITLE
有多列中文时， 中文列不对齐

### ISSUE THREAD

**Issue by manateelazycat** [mumu-lhl/eaf-pyqterminal#21]
当有多列中文时， VTE 控件的终端可以让列对齐， eaf-pyqterminal 还不行。

两边字体都是 FiraCode Nerd Font Mono

![截图 2023-06-22 12-47-23](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/e7873ad3-c20a-41c9-954e-c078390b0d2f)

![截图 2023-06-22 12-47-45](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/07163274-cdef-47df-9255-5fd9c7b77018)

**Comment by mumu-lhl** [comment]
这个问题是由于两宽字符判断的部分有 bug 而导致的，现在最新版中应该已经修复了

**Comment by manateelazycat** [comment]
已经修复了。
