### ISSUE TITLE
在终端下，vim不能编辑文件

### ISSUE THREAD

**Issue by sxqsfun** [mumu-lhl/eaf-pyqterminal#24]
在终端下，打开vim编辑文件时，按键会失效，不能操作

**Comment by mumu-lhl** [comment]
更新一下，已经修复了

**Comment by sxqsfun** [comment]
神速！刚更新试了，没问题。感谢感谢

**Comment by sxqsfun** [comment]
ssh远程使用vim时，方向键会失效。本地使用正常

**Comment by sxqsfun** [comment]
> 更新一下，已经修复了

ssh远程使用vim时，方向键会失效。本地使用正常

**Comment by sxqsfun** [comment]
> 看一下`*eaf*`里有什么相关的报错吗？

刚打开eaf debug 看了下，没有报错信息

**Comment by sxqsfun** [comment]
![2023-08-29_17-46](https://github.com/mumu-lhl/eaf-pyqterminal/assets/6365447/d04de82b-7925-4139-afa9-0c19a2bcf17c)

**Comment by mumu-lhl** [comment]
无法复现

试下其他终端有没有这个问题吧

**Comment by sxqsfun** [comment]
> 无法复现
> 
> 试下其他终端有没有这个问题吧

用 alacritty 是没有问题的。在pyqterminal中，ssh远程后，用 vim 打开文件，此时方向键能正常使用。按 i 进入编辑模式后，方向键失效，按方向键会退出编辑模式，vim下方提示：E388: Couldn't find definition

可能是我之前的问题描述得太简单了，麻烦再帮忙看看
