### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mumu-lhl** [mumu-lhl/eaf-pyqterminal#25]
预计在年底前完成这些任务：

- [x] 完成 #23
- [ ] ~修复部分字体渲染错误~
- [ ] ~支持与 holo-layer 集成实现浮动终端~
- [X] 重构
- [X] 支持 retina

完成这些任务后，我打算放弃用 Emacs。我今年都在改进自己用的工具（如一些 Emacs 插件），虽然终将会改到一个让自己比较满意的时候，但不知道还会再改多长时间，我现在清楚我更需要的是开箱即用的工具。这个项目未来可能不会再增加新的功能了，但还是会处理 issue 和 PR 的。

**Comment by manateelazycat** [comment]
手动点赞
