### ISSUE TITLE
btop 会是一个非常好的测试程序

### ISSUE THREAD

**Issue by manateelazycat** [mumu-lhl/eaf-pyqterminal#30]
我在日常使用中， 经常会遇到对齐有小瑕疵的场景。

建议测试一下 btop, 如果 btop 可以稳定的对齐渲染， 很多其他程序的渲染问题应该也可以一并修复。

**Comment by manateelazycat** [comment]
![截图 2024-05-05 00-40-14](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/a0768311-a94a-4232-8eaa-fbf9f6d21601)

![截图 2024-05-05 00-40-27](https://github.com/mumu-lhl/eaf-pyqterminal/assets/237487/d1dc0bc1-2a39-428d-8c7f-702728e8394f)
上面是我的对比截图

**Comment by mumu-lhl** [comment]
以前试过很多办法解决，现在再去解决这个问题才发现解决方法如此简单🤣

**Comment by manateelazycat** [comment]
大佬， 手动点赞啊！

**Comment by manateelazycat** [comment]
@mumu-lhl btop 的截图可以放到 README 中吗？ 

我相信 btop 这种复杂布局的绘制对齐对于常用 eshell 的 Emacser 来说还是非常震惊的。 ;)
