### ISSUE TITLE
bug: wrong terminal rendering

### ISSUE THREAD

**Issue by nanakura** [mumu-lhl/eaf-pyqterminal#35]
目前界面是这个样子
![64866612147b64aa7726077571998097](https://github.com/user-attachments/assets/7d497e67-07ae-4405-86f8-a29562a8d813)
按一下空格变成下面这样
![5f7d2be82d21a17d656caf965ff070a7](https://github.com/user-attachments/assets/bb81f4cc-5f64-485f-b18e-b8867c81d2cd)
这个有什么解决办法吗

**Comment by nanakura** [comment]
然后渲染有一些缺失
![image](https://github.com/user-attachments/assets/c8398525-fe02-4690-97ef-7b9b97f66e18)

正常应该是下面这样
![image](https://github.com/user-attachments/assets/6a418908-5ab9-45a2-89b6-45ce23167ed2)

**Comment by manateelazycat** [comment]
感觉像字体没有配置对

**Comment by manateelazycat** [comment]
@nanakura 参考 https://github.com/mumu-lhl/eaf-pyqterminal/issues/17#issuecomment-1596133701

**Comment by nanakura** [comment]
> @nanakura 参考 [#17 (comment)](https://github.com/mumu-lhl/eaf-pyqterminal/issues/17#issuecomment-1596133701)

没有效果
![image](https://github.com/user-attachments/assets/60f84afe-64cb-456e-8dbe-6305ecff02ab)
而且我本来用的就是nerd font，跟这个应该没关系
![image](https://github.com/user-attachments/assets/e85fb6d1-cc2e-42c5-9223-2a21106d62ff)

**Comment by nanakura** [comment]
如何指定shell为gitbash而不是powershell，我试了下似乎gitbash应该没这个问题

**Comment by mumu-lhl** [comment]
> 如何指定shell为gitbash而不是powershell

重新定义 `eaf--generate-terminal-command` 返回 gitbash：

```elisp
(defun eaf--generate-terminal-command ()
  "gitbash.exe")
```

**Comment by nanakura** [comment]
关于powershell的渲染错误，我怀疑是ohmyposh导致的
